name: Release Drafter

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

permissions:
  contents: write
  pull-requests: write

jobs:
  write-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get previous tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: sprint-01-release
      - name: run script
        run: |
          sprint_number=$(echo "${{ steps.tag.outputs.tag }}" | sed -E 's/^sprint-([0-9]+)-release$/\1/')
          next_sprint_number=$((sprint_number + 1))
          echo "NEXT_SPRINT_NUMBER=$next_sprint_number" >> $GITHUB_ENV
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
