name: Code Formatting and Linting
on:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install PDM
        run: |
          pip install pdm
          pdm install
      - name: Run Prettify (Code Formatting and Linting)
        run: pdm run prettify
        
