name: Check release draft

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check labels on PR
        run: |
          labels="${{ github.event.pull_request.labels.*.name }}"
          if [[ $labels == *"release: hot-fix"* || $labels == *"release: feature"* || $labels == *"release: bug-fix"* || $labels == *"release: sprint-deliverables"* || $labels == *"release: ignore"* ]]; then
            echo "At least one valid release label found. Merge allowed."
          else
            echo "No valid release label found. Merge blocked."
            exit 1
          fi
      
