name: Check PR Label

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has specific label
        uses: actions/github-script@v5
        with:
          script: |
            const labels = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const hasLabel = labels.data.some(label => label.name === 'test');

            if (!hasLabel) {
              core.setFailed('Pull request does not have the required label.');
            }
