name: Check PR Label

on:
  pull_request:
       types: [opened, labeled, unlabeled, synchronize]
jobs:
  check_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has specific label
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          valid-labels: 'bug, enhancement'
