name: Check release draft

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled
jobs:
  verify-labels:
    runs-on: ubuntu-latest
    name: Verify labels
    if: github.event.pull_request.merged == false
    steps:
      - uses: actions/checkout@v3
      - name: Verify labels
        id: action-verify-labels
        uses: mauroalderete/action-verify-labels@v1
        with:
          some: 'release: feature'
