name: Check release draft

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has a release label
        if: (contains(github.event.pull_request.labels.*.name, 'release:- feature') == 'false' || contains(github.event.pull_request.labels.*.name, 'release:- bug-fix') == 'false' || contains(github.event.pull_request.labels.*.name, 'release:- hot-fix') == 'false' || contains(github.event.pull_request.labels.*.name, 'release:- sprint-deliverables') == 'false' || contains(github.event.pull_request.labels.*.name, 'release:- ignore') == 'false')
        run: |
          echo "This PR has a release label"
          exit 1
